mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from api.models import MovieResource

movie_resource= MovieResource()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('api/',include(movie_resource.urls))


]

polls/urls.py
from django.urls import path

from . import views
app_name='moives'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/',views.home,name='home'),
    path('home/<int:movie_id>',views.detail,name='detail'),

]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from polls.models import Movie


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name='home'

polls/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=225)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=225)
    number = models.IntegerField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

polls/views.py
from django.shortcuts import render , get_object_or_404

# Create your views here.
from django.http import HttpResponse ,Http404
from .models import Movie


def index(request):
    return render(request, 'mysite/index.html')


def home(request):
    movies = Movie.objects.all()
    output = ','.join([m.title for m in movies])
    return render(request, 'mysite/home.html', {'movies': movies})


def detail(request, movie_id):
    movie=get_object_or_404(Movie,pk=movie_id)
    return render(request,'mysite/details.html',{'movie':movie})

polls/templates/mysite/details.html
{% extends 'base.html' %}
{% block content %}
    <dl>
        <dt>Title</dt>
        <dl>{{ movie.title }}</dl>
        <dt>Number</dt>
        <dl>{{ movie.number }}</dl>
        <dt>Genre</dt>
        <dl>{{ movie.genre }}</dl>
        <dt>Date</dt>
        <dl>{{ movie.date }}</dl>
    </dl>
{% endblock %}

polls/templates/mysite/home.html
{% extends 'base.html' %}
{% block content %}

    <html>
    <head>
        <title>home</title>

    </head>
    <body>


{#    <h1>WELCOME</h1>#}
    <table class="table table-bordered table-hover">
        <thead>

                <th>Title</th>
                <th>Genre</th>
                <th>Date</th>
                <th>Number</th>

        </thead>

        <tbody>
            {% for movie in movies %}
                <tr>
                    <td>
                        <a href="{% url 'moives:detail' movie.id %}">{{ movie.title   }}</a>
                    </td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.date }}</td>
                    <td>{{ movie.number }}</td>
                </tr>

            {% endfor %}
        </tbody>
    </table>
    </body>
    </html>

{% endblock %}

polls/templates/mysite/index.html
{% extends 'base.html' %}
{% block content %}

    <html>
    <head>
        <title>home</title>

    </head>
    <body>


    <h1>WELCOME HOME</h1>
    </body>
    </html>



{% endblock %}

templates/mysite/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      {#    <title>Hello, world!</title>#}
  </head>
  <body>
<button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">
  Single toggle
</button>
  {% extends 'nav.html' %}

<main class="container" >
    {% block content  %}


    {% endblock %}

</main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/mysite/nav.html
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url  'moives:home' %}">Index</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'moives:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>



{% block content  %}

{% endblock %}